/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        // Catppuccin Mocha palette
        base: '#1e1e2e',
        mantle: '#181825',
        crust: '#11111b',
        surface0: '#313244',
        surface1: '#45475a',
        surface2: '#585b70',
        overlay0: '#6c7086',
        overlay1: '#7f849c',
        overlay2: '#9399b2',
        subtext0: '#a6adc8',
        subtext1: '#bac2de',
        text: '#cdd6f4',
        rosewater: '#f5e0dc',
        flamingo: '#f2cdcd',
        pink: '#f5bde6',
        mauve: '#cba6f7',
        red: '#f38ba8',
        maroon: '#eba0ac',
        peach: '#fab387',
        yellow: '#f9e2af',
        green: '#a6e3a1',
        teal: '#94e2d5',
        sky: '#89dceb',
        sapphire: '#74c7ec',
        blue: '#89b4fa',
        lavender: '#b4befe',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.text'),
            '--tw-prose-headings': theme('colors.text'),
            '--tw-prose-lead': theme('colors.subtext1'),
            '--tw-prose-links': theme('colors.blue'),
            '--tw-prose-bold': theme('colors.text'),
            '--tw-prose-counters': theme('colors.subtext1'),
            '--tw-prose-bullets': theme('colors.subtext0'),
            '--tw-prose-hr': theme('colors.surface0'),
            '--tw-prose-quotes': theme('colors.subtext1'),
            '--tw-prose-quote-borders': theme('colors.surface1'),
            '--tw-prose-captions': theme('colors.subtext0'),
            '--tw-prose-code': theme('colors.peach'),
            '--tw-prose-pre-code': theme('colors.text'),
            '--tw-prose-pre-bg': theme('colors.mantle'),
            '--tw-prose-th-borders': theme('colors.surface1'),
            '--tw-prose-td-borders': theme('colors.surface0'),
          },
        },
        lg: {
          css: {
            fontSize: '1.125rem',
            lineHeight: '1.7',
            h2: {
              marginTop: '2em',
              marginBottom: '1em',
              fontSize: '1.5em',
              fontWeight: '700',
            },
            h3: {
              marginTop: '1.6em',
              marginBottom: '0.8em',
              fontSize: '1.25em',
              fontWeight: '600',
            },
            h4: {
              marginTop: '1.4em',
              marginBottom: '0.6em',
              fontSize: '1.125em',
              fontWeight: '600',
            },
            blockquote: {
              borderLeftColor: theme('colors.mauve'),
              borderLeftWidth: '4px',
              paddingLeft: '1rem',
              fontStyle: 'italic',
              backgroundColor: theme('colors.mantle'),
              padding: '1rem',
              borderRadius: '0.5rem',
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            code: {
              backgroundColor: theme('colors.surface0'),
              padding: '0.25rem 0.375rem',
              borderRadius: '0.25rem',
              fontSize: '0.875em',
              fontWeight: '500',
            },
            pre: {
              backgroundColor: theme('colors.mantle'),
              border: `1px solid ${theme('colors.surface0')}`,
              borderRadius: '0.5rem',
              padding: '1rem',
            },
            'pre code': {
              backgroundColor: 'transparent',
              padding: '0',
              borderRadius: '0',
              fontSize: 'inherit',
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
}